In [92]:
import torch
from itertools import combinations, permutations

The cell below creates 5 tensors, `a`, `b`, `c`, `d`, and `e`.
We will work with these tensors in the notebook to practice basic tensor operations.

In [44]:
#@title Run this cell (but don't peek!)
a = torch.tensor(2.5)
b = torch.randn(10)
c = torch.randn(4, 4)
d = torch.randn(4, 4, 4)
e = torch.randn(12, 4, 4, 4)

In [57]:
tensors = [a, b, c, d, e]
tensor_names = ['a','b','c','d','e']

For each of the 5 tensors, print the shape of each tensor.

In [46]:
for t in tensors:
    print(t.shape)

torch.Size([])
torch.Size([10])
torch.Size([4, 4])
torch.Size([4, 4, 4])
torch.Size([12, 4, 4, 4])


For each of the 5 tensors, print the number of values stored in each tensor.

In [47]:
for t in tensors:
    print(t.numel())

1
10
16
64
768


For each of the 5 tensors, print the rank of the tensor.

In [48]:
for t in tensors:
    print(t.ndim)

0
1
2
3
4


Create a 3x3 tensor filled with values sampled from a normal distribution with a mean of 0 and standard deviation of 1.

In [49]:
torch.randn(3, 3)

tensor([[ 0.0669,  0.0833,  1.3159],
        [ 0.2171, -2.0850, -0.7521],
        [ 0.6914,  0.1548, -0.0593]])

Create a rank 1 tensor with digits 0-9

In [50]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a tensor with all ones where the shape is `[2, 4, 6]`

In [51]:
torch.ones(2, 4, 6)

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

Create a tensor of all zeros with the same shape as the tensor `b`

In [52]:
torch.zeros_like(b)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Which tensors in `tensors` can be added together?
Which can't?
Why?

In [60]:
tensors_with_names = list(zip(tensor_names, tensors))

In [93]:
combos = list(permutations(tensors_with_names, 2))

In [94]:
for (name_1, tensor_1), (name_2, tensor_2) in combos:
    try:
        tensor_1 + tensor_2
        print(f"Tensor 1: {name_1}, shape = {tensor_1.shape}\nTensor 2: {name_2}, shape = {tensor_2.shape}\n")
    except:
        print(f"{name_1} and {name_2} could not be added.\n")

Tensor 1: a, shape = torch.Size([])
Tensor 2: b, shape = torch.Size([10])

Tensor 1: a, shape = torch.Size([])
Tensor 2: c, shape = torch.Size([4, 4])

Tensor 1: a, shape = torch.Size([])
Tensor 2: d, shape = torch.Size([4, 4, 4])

Tensor 1: a, shape = torch.Size([])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])

Tensor 1: b, shape = torch.Size([10])
Tensor 2: a, shape = torch.Size([])

b and c could not be added.

b and d could not be added.

b and e could not be added.

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: a, shape = torch.Size([])

c and b could not be added.

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: d, shape = torch.Size([4, 4, 4])

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])

Tensor 1: d, shape = torch.Size([4, 4, 4])
Tensor 2: a, shape = torch.Size([])

d and b could not be added.

Tensor 1: d, shape = torch.Size([4, 4, 4])
Tensor 2: c, shape = torch.Size([4, 4])

Tensor 1: d, shape = torch.Size([4, 4, 4])
Tensor 2

Which tensors in `tensors` can be multiplied together using an element-wise operation?
Which can't?
Why?

In [73]:
for (name_1, tensor_1), (name_2, tensor_2) in combos:
    try:
        tensor_1 * tensor_2
        print(f"Tensor 1: {name_1}, shape = {tensor_1.shape}\nTensor 2: {name_2}, shape = {tensor_2.shape}\n")
    except:
        print(f"{name_1} and {name_2} could not be multiplied.\n")

Tensor 1: a, shape = torch.Size([])
Tensor 2: b, shape = torch.Size([10])

Tensor 1: a, shape = torch.Size([])
Tensor 2: c, shape = torch.Size([4, 4])

Tensor 1: a, shape = torch.Size([])
Tensor 2: d, shape = torch.Size([4, 4, 4])

Tensor 1: a, shape = torch.Size([])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])

b and c could not be multiplied.

b and d could not be multiplied.

b and e could not be multiplied.

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: d, shape = torch.Size([4, 4, 4])

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])

Tensor 1: d, shape = torch.Size([4, 4, 4])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])



Which tensors in `tensors` can be multiplied together using matrix multiplication?
Which can't?
Why?

In [78]:
for (name_1, tensor_1), (name_2, tensor_2) in combos:
    try:
        tensor_1 @ tensor_2
        # torch.matmul(tensor_1, tensor_2)
        # tensor2.matmul(tensor_1)
        print(f"Tensor 1: {name_1}, shape = {tensor_1.shape}\nTensor 2: {name_2}, shape = {tensor_2.shape}\n")
    except:
        print(f"{name_1} and {name_2} could not be multiplied.\n")

a and b could not be multiplied.

a and c could not be multiplied.

a and d could not be multiplied.

a and e could not be multiplied.

b and c could not be multiplied.

b and d could not be multiplied.

b and e could not be multiplied.

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: d, shape = torch.Size([4, 4, 4])

Tensor 1: c, shape = torch.Size([4, 4])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])

Tensor 1: d, shape = torch.Size([4, 4, 4])
Tensor 2: e, shape = torch.Size([12, 4, 4, 4])



Write a function for a rectified linear unit.
This function should take in a tensor, and return another tensor where the positive values remain the same but the negative values are replaced by zeros. 
Please use only `torch` functions and `Tensor` mehtods and do not use any loops.

In [87]:
c.masked_fill(c < 0, 0)

tensor([[0.0000, 0.0000, 0.0000, 0.4122],
        [0.8625, 0.0000, 0.0000, 0.0000],
        [0.4531, 0.0000, 0.4959, 0.3654],
        [0.0000, 0.3215, 0.0000, 1.8003]])

In [88]:
def relu(t):
    return t.masked_fill(t < 0, 0)

In [91]:
for t in tensors:
    assert relu(t).min() >= 0